title: "Writeups"
# Baseurl
baseurl: "writeups"

# Build settigs
markdown: kramdown

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - Tryhackme
theme: jekyll-theme-hacker